# http://stackoverflow.com/questions/1670154/convert-a-ruby-on-rails-app-from-sqlite-to-mysql
# http://stackoverflow.com/questions/4546698/library-not-loaded-libmysqlclient-16-dylib-error-when-trying-to-run-rails-serv
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/development
  pool: 5
  # username: root
  # password: admin
  socket: /tmp/mysql.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/test
  pool: 5
  # username: root
  # password: admin
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: db/production
  pool: 5
  # username: root
  # password: admin
  socket: /tmp/mysql.sock