require 'simplecov'
SimpleCov.start

require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'rspec/autorun'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.after(:each) do
    [Node, Resource, User, Admin, Complaint].each do |table|
      table.delete_all
    end
    CASClient::Frameworks::Rails::Filter.fake(nil, nil)
  end
end

def ldap_lookup(calnet_id)
  ldap = Net::LDAP.new(
    host: 'ldap.berkeley.edu',
    port: 389
  )
  if ldap.bind
    ldap.search(
      base:          "ou=people,dc=berkeley,dc=edu",
      filter:        Net::LDAP::Filter.eq( "uid", calnet_id.to_s ),
      attributes:    %w[ displayName ],
      return_result: true
    ).first.displayName.first
  else
    flash[:error] = "Can't connect to LDAP to get user's name"
  end
end